language: go

go:
  - "1.11.x"

os:
  - linux
  - osx

dist: xenial

sudo: false

before_install:
  - go get -u github.com/golangci/golangci-lint
  - cd $(go env GOPATH)/src/github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install -ldflags "-X 'main.version=$(git describe --tags)' -X 'main.commit=$(git rev-parse --short HEAD)' -X 'main.date=$(date)'"
  - go get -u github.com/goreleaser/goreleaser

install: true

env:
  - GO111MODULE=on

script:
  - make lint && make vet
  - make test
  - make build
